Solution/EstateAgency/config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { :sessions => "accounts/sessions"}, format: false
  resources :estates, format: false
  resources :users, format: false
  get '/accounts/my' => 'accounts#my'
  resources :login, format: false
  resources :main, format: false
  namespace :api do
    get '/helpers/pagenumber', to: 'helpers#page_number', format: false
    resources :demo_estates, only: [:index], format: false
    resources :estate_types, only: [:index], format: false
    resources :estates, only: [:show, :index, :destroy, :update, :create], format: false do
      resources :estate_revisions, only: [:index], format: false
    end
    resources :estate_revisions, only: [:show, :destroy, :update, :create], format: false

    resources :users, only: [:show, :index, :destroy, :update, :create], format: false do
      resources :accounts, only: [:index], format: false
    end
    resources :accounts, only: [:show, :destroy, :update, :create], format: false
    resources :city_areas, only: [:index], format: false
  end

   root to: "main#index"

end

Solution/EstateAgency/app/models/estate_revision.rb
class EstateRevision < ActiveRecord::Base
	belongs_to :account
	belongs_to :estate
  after_create :set_estate_actualized_date

  @@includes = [:estate, :account => [:user]]
  @@revision_results = {
      1 => { :value => 'for_rent', :label => 'Сдается'},
      3 => { :value => 'not_rent_more', :label => 'Не сдается'}
  }
  def self.includes
    @@includes
  end

  def self.results
    @@revision_results
  end

  protected

  def set_estate_actualized_date
    self.estate.actualized_at = self.created_at
    self.estate.save
  end
end

Solution/EstateAgency/app/controllers/api/estate_revisions_controller.rb
module Api
  class EstateRevisionsController < ApplicationController
    before_action :set_estate_revision, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_account!
    before_action :active_account!
    before_action :manager_account!, only: [:create, :update, :destroy]

    def initialize
      @revision_view_mapper = EstateRevisionToViewModelMapper.new
      @revision_updater = EstateRevisionUpdater.new
    end

    def index
      @estate_revisions = EstateRevision.where(:estate_id => params[:estate_id]).order(created_at: :desc)
      view_models = @estate_revisions.collect do |revision|
        @revision_view_mapper.map revision
      end
      render_json view_models
    end

    def show
      render_json @revision_view_mapper.map @estate_revision
    end

    def destroy
      EstateRevision.destroy @estate_revision.id
      render_json @estate_revision.id
    end

    def update
      model_params = @revision_updater.get_updates params
      result = EstateRevision.update(params[:id], model_params)
      render_json @revision_view_mapper.map result
    end

    def create
      model_params = @revision_updater.get_updates params
      result = EstateRevision.create(model_params)
      render_json @revision_view_mapper.map result
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_estate_revision
      @estate_revision = EstateRevision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estate_revision_params
      params[:estate_revision]
    end
  end
end

Solution/EstateAgency/app/helpers/estate_revisions_helper.rb
module EstateRevisionsHelper
end

Solution/EstateAgency/app/views/estate_revisions/_estate_revisions_list_template.erb
<script type="text/html" id="estate-revisions-list-template">
    <input type="checkbox" class="toggle-chb"  id="revisions-list-chb" />
    <div class="title-row c-manager-mode">
        <div class="row">
            <div class="col-xs-10">
                <div class="c-page-title title-text">
                    Актуализация
                    <label for="revisions-list-chb" class="expand-btn mdi mdi-chevron-right"></label>
                </div>
            </div>
            <div class="col-xs-2 text-xs-right">
                <span class="mdi mdi-plus-circle-outline action-btn c-new-revision-btn c-manager-mode" title="Внести информацию"></span>
            </div>
        </div>
    </div>
    <span class="c-items c-manager-mode expandable-list"></span>
</script>

<script type="text/html" id="estate-revisions-list-item-template">
    <h5>{{created_at}} - {{revision_result}}</h5>
    <span class="remove-item-btn c-remove mdi mdi-close c-manager-mode"></span>
</script>

<script id="create-revision-dialog-template" type="text/html">
    <div class="overlay c-close-dialog"></div>
    <div class="popup popup-l">
        <div class="popup-head">
            <div class="popup-close mdi mdi-close c-close-dialog"></div>
            Результат прозвона
        </div>
        <div class="popup-body form">
            <div class="row">
                <div class="col-xs-5 text-xs-right field-label">Дата прозвона</div>
                <div class="col-xs-7">
                    <input type="text" class="datepicker c-created-at">
                </div>
            </div>
            <div class="row">
                <div class="col-xs-5 text-xs-right field-label">Результат</div>
                <div class="col-xs-7">
                    <select class="c-result"></select>
                </div>
            </div>
        </div>
        <div class="popup-footer">
            <button class="btn light-btn c-close-dialog">Отмена</button>
            <button class="btn light-btn c-accept">Далее</button>
        </div>
    </div>
</script>

Solution/EstateAgency/app/views/estate_revisions/index.html.erb
<h1>Listing estate_revisions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estate_revisions.each do |estate_revision| %>
      <tr>
        <td><%= link_to 'Show', estate_revision %></td>
        <td><%= link_to 'Edit', edit_estate_revision_path(estate_revision) %></td>
        <td><%= link_to 'Destroy', estate_revision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estate revision', new_estate_revision_path %>